name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@v5
      - name: Install linters
        run: |
          uv pip install --system --upgrade pip
          uv pip install --system ruff black
          if [ -f pyproject.toml ]; then uv pip install --system .; fi
      - name: Ruff
        run: ruff check .
      - name: Black
        run: black --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@v5
      - name: Install test deps
        run: |
          uv pip install --system --upgrade pip
          uv pip install --system pytest
          if [ -f pyproject.toml ]; then uv pip install --system .; fi
      - name: Pytest
        run: pytest -q

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/fraud-service
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and (optionally) push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}